<?php

/**
 * @file
 * Contains pineapple_mail.module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_mail().
 */
function pineapple_mail_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'review_content':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Subject: @title', array('@title' => $params['title']), $options);
      $message['body'][] = Html::escape($params['message']);
      break;
  }
}

function pineapple_mail_send_mail($entity) {
  $mailManager = \Drupal::service('plugin.manager.mail');
  $module = 'pineapple_mail';
  $key = 'review_content';
  $to = \Drupal::config('system.site')->get('mail');
  $entity_link = $entity->toUrl()->setAbsolute()->toString();
  $entity_title = $entity->label();
  $params['message'] = 'The user ' . \Drupal::currentUser()->getAccountName() . ' indicated that ' . $entity_title . ' is ready for review. View it here: ' . $entity_link;
  $params['title'] = $entity_title . ' is ready to review';
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = true;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== true) {
    $message = 'There was a problem notifying the administrator about your content changes, please try again. If the problem persists, contact the site administrator.';
    \Drupal::messenger()->addError($message);
    \Drupal::logger('mail-log')->error($message);
  }
  else {
    $message = 'Your content has been flagged as ready for review and will be reviewed and published by the site administrator.';
    \Drupal::messenger()->addMessage($message);
    \Drupal::logger('mail-log')->notice($message);
  }
}

/**
 * Implements hook_node_presave().
 *
 * @param /Drupal\Core\Entity\EntityInterface
 */
function pineapple_mail_node_presave($entity) {
  $entity_type = $entity->getType();
  if ($entity_type == 'article' || $entity_type == 'recipe') {
    // Get the value of the ready to review field.
    $ready_to_review = $entity->get('field_ready_to_review')->getValue()[0]['value'];

    // If the ready to review field is checked, and the node is unpublished.
    if ($ready_to_review == 1 && !$entity->isPublished()) {
      pineapple_mail_send_mail($entity);
    }

    // After email is sent, uncheck the ready to review field.
    $entity->set('field_ready_to_review', 0);
  }
}
