module.exports = function(grunt) {
  // Project configuration.
  const sass = require('node-sass');
  require('load-grunt-tasks')(grunt);
  // Initialise Grunt config.
  grunt.initConfig({
    sass: {
      options: {
        implementation: sass,
        // Generate CSS sourcemap from sass files.
        sourceMap: true,
      },
      dist: {
        options: {
          // Minifies the CSS file.
          outputStyle: 'compressed'
        },
        files: {
          // Converts sass files into CSS file and puts it into the build folder.
          'css/pineapple.styles.min.css': 'sass/pineapple.styles.scss'
        }
      }
    },
    sass_globbing: {
      files: {
        'sass/core/__core.scss': 'sass/core/**/*.scss',
        'sass/base/__base.scss': 'sass/base/**/*.scss',
        'sass/layouts/__layouts.scss': 'sass/layouts/**/*.scss',
        'sass/components/__components.scss': 'sass/components/**/*.scss'
      },
      options: {
        useSingleQuotes: false,
        signature: '// Generated by grunt-sass-globbing, do NOT edit manually.'
      }
    },
    concat:{
      js: {
        // Looks into directories inside js and then looks for files with the .js extensions.
        src: ['assets/js/**/*.js'],
        // Combines all files into one file and places into the build folder.
        dest: 'js/pineapple.behavior.min.js'
      }
    },
    uglify: {
      build: {
        files: [{
          // Minifies script.min.js inside the build folder.
          src: 'js/pineapple.behavior.min.js',
          dest: 'js/pineapple.behavior.min.js'
        }]
      }
    },
    watch: {
      sass: {
        // Watches for changes in the following files/folders and runs the appropriate tasks.
        files: ['sass/**/*.scss', 'assets/js/*.js'],
        tasks: ['sass', 'concat']
      }
    },
  });

  // Load tasks.
  grunt.loadNpmTasks('grunt-sass');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-sass-globbing');

  // Register tasks.
  grunt.registerTask('default', ['sass', 'sass_globbing', 'concat', 'uglify']);
  grunt.registerTask('serve', ['watch']);

};
