<?php

/**
 * @file
 * Contains pineapple_general.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_help().
 */
function pineapple_general_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pineapple_general module.
    case 'help.page.pineapple_general':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for general site-wide functions.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function pineapple_general_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  if (key_exists('form_id', $form_state->getBuildInfo())) {
    $user_roles = \Drupal::currentUser()->getRoles();
    $build_info = $form_state->getBuildInfo();
    // If the field is on the article or recipe create or edit form, run code.
    switch ($build_info['form_id']) {
      case 'node_article_form':
      case 'node_recipe_form':
      case 'node_article_edit_form':
      case 'node_recipe_edit_form':
        $items = $context['items'];
        $field = $items->getName();
        /* If field name is either field_a_summary or field_r_summary, set the
        maxlength to be 200 characters and the countdown to show. */
        if ($field == 'field_a_summary' || $field == 'field_r_summary') {
          $element['#maxlength_js'] = TRUE;
          $element['value']['#maxlength_js'] = TRUE;
          $maxlength_js = 200;
          $element['value']['#attributes']['maxlength'] = $maxlength_js;
          $element['#attributes']['maxlength'] = $maxlength_js;
        }

      if (!in_array('administrator', $user_roles)) {
        if($field == 'moderation_state') {
          $element['state']['#description'] = 'Your changes will be reviewed and be published when approved by an administrator.';
        }
      }
      break;
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function pineapple_general_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_recipe_form':
    case 'node_recipe_edit_form':
      // For each paragraph in the body field, assign key.
      foreach ($form['field_r_body']['widget'] as $field_key => $field) {
        if (isset($field['#paragraph_type']) && $field['#paragraph_type'] == 'method') {
          $i_count = 1;
          foreach ($field['subform']['field_p_m_instruction']['widget'] as $i_key => $instruction) {
            if (isset($instruction['#paragraph_type']) && $instruction['#paragraph_type'] == 'instruction') {
              /* Set paragraph_label to equal the value of paragraph type, with
              the first letter capitalised and the i_count incrementing by 1. */
              $paragraph_label = ucfirst($instruction['#paragraph_type']). ' ' . $i_count++;
              /* This path does not use variables created above because the $form
              variable is passed by reference through the form alter function.
              This allows us to alter it. */
              $form['field_r_body']['widget'][$field_key]['subform']['field_p_m_instruction']['widget'][$i_key]['top']['type']['label']['#markup'] = '<span class="paragraph-type-label">' . $paragraph_label. '</span>';
            }
          }
        }
      }
      $user_roles = \Drupal::currentUser()->getRoles();
      // If the user roles array contains "recipe editor", restrict access to fields.
      if (in_array('recipe_editor', $user_roles)) {
        $form['field_r_featured']['#access'] = FALSE;
        $form['field_r_highlighted']['#access'] = FALSE;
      }
    break;

    case 'comment_article_comment_form':
    case 'comment_recipe_comment_form':
      $form['actions']['submit']['#value'] = t('Post');
    break;
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function pineapple_general_field_widget_entity_reference_paragraphs_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $user_roles = \Drupal::currentUser()->getRoles();
  /* If the field_p_c_component exists and if the user does not have the administrator
  role. */
  if (isset($element['subform']['field_p_c_component']) && !in_array('administrator', $user_roles)) {
    /* For each item in the widget array, if the paragraph type variable exists,
    and is equal to image paragraph, or image_grid. */
    foreach ($element['subform']['field_p_c_component']['widget'] as &$paragraph) {
      if (isset($paragraph['#paragraph_type'])) {
        if ($paragraph['#paragraph_type'] == 'image_paragraph' || $paragraph['#paragraph_type'] == 'image_grid') {
          // If the hero image or the image grid item fields exist.
          if (isset($paragraph['subform']['field_p_ip_hero_image']) || isset($paragraph['subform']['field_p_ig_item'])) {
            $paragraph['subform']['field_p_ip_hero_image']['#access'] = FALSE;

            /* For each item in the widget array, if the grid item link field exists
            restrict access to the link field. */
            foreach ($paragraph['subform']['field_p_ig_item']['widget'] as &$paragraph_field) {
              if (isset($paragraph_field['subform']['field_p_gi_link'])) {
                $paragraph_field['subform']['field_p_gi_link']['#access'] = FALSE;
                /* For each item in the widget array, if the hero image field exists,
                restrict access to it. */
                foreach ($paragraph_field['subform']['field_p_gi_image']['widget'] as &$image_paragraph_item) {
                  if (isset($image_paragraph_item['subform']['field_p_ip_hero_image'])) {
                    $image_paragraph_item['subform']['field_p_ip_hero_image']['#access'] = FALSE;
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  if ($element['#paragraph_type'] == 'components') {
    $links_to_remove = [
      'add_more_button_call_to_action',
      'add_more_button_slideshow',
      'add_more_button_content_spotlight',
      'add_more_button_content_authors_component'
    ];
    $add_more_links = &$element['subform']['field_p_c_component']['widget']['add_more']['operations']['#links'];
    /* If add_more_links exists, and the user does not have the administrator role,
    if an add_more variable is in the links_to_remove array, remove it. */
    if (isset($add_more_links) && !in_array('administrator', $user_roles)) {
      foreach ($add_more_links as $key => $add_more) {
        if (in_array($key, $links_to_remove)) {
          unset($add_more_links[$key]);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_webform().
 */
function pineapple_general_preprocess_webform(&$variables) {
  $wfid = $variables['element']['#webform_id'];
  $wf = \Drupal\webform\Entity\Webform::load($wfid);
  $variables['title'] = $wf->label();
}

/**
 * Set dynamic allowed values for the content author field(s).
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 * This functions is called in the field.storage.node files for the content author fields for the nodes which use it.
 *
 * Do drush cim -y after making changes to the config files (to call one of these functions), in order to import the config changes.
 *
 * @see button_color_select_list_values()
 * This function sets the options of the select field, in order to create the possibility for more color options to be added in the future.
 */
function button_color_select_list_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $options = [
    'primary' => 'Primary',
    'secondary' => 'Secondary',
    'tertiary' => 'Tertiary',
    'underlined' => 'Underlined'
  ];

  return $options;
}
