<?php

/**
 * @file
 * Contains pineapple_general.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements pineapple_hello_world_theme().
 * Variables must be defined here.
 */
function pineapple_hello_world_theme($existing, $type, $theme, $path) {
  return [
    'hello_world' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}


