<?php

/**
 * @file
 * Contains pineapple_recipe.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function pineapple_recipe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pineapple_recipe module.
    case 'help.page.pineapple_recipe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for the recipe content type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function pineapple_recipe_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  $currentUser = \Drupal::currentUser();
  $currentAuthor = $currentUser->getDisplayName();
  $currentAuthorId = $currentUser->id();
  if ($form_id == 'node_recipe_form') {
    if (isset($form['field_r_content_author'])) {
      $form['field_r_content_author']['widget']['#options'] = array('Author' => $currentAuthor);
    }
  }

  if ($form_id == 'node_recipe_edit_form') {
    if (\Drupal::routeMatch()->getParameter('node')) {
      $node = \Drupal::routeMatch()->getParameter('node');
      if (isset($node)) {
        $creatorId = $node->getOwnerId();
        $creator = $node->getOwner()->getDisplayName();

        if (isset($form['field_r_content_author'])) {
          if ($creatorId === $currentAuthorId){
            $form['field_r_content_author']['widget']['#options'] = array('Author' => $creator);
          } else {
            $form['field_r_content_author']['widget']['#options'] = array(
              'Creator' => $creator,
              'Current Author' => $currentAuthor
            );
          }
        }
      }
    }
  }
}
