<?php

/**
 * @file
 * Contains pineapple_recipe.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pineapple_recipe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pineapple_recipe module.
    case 'help.page.pineapple_recipe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for the recipe content type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pineapple_recipe_form_node_recipe_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if (isset($form['field_r_content_author'])) {
    $currentUser = \Drupal::currentUser();
    $author = $currentUser->getDisplayName();
    $form['field_r_content_author']['widget']['#options'] = array('Author' => $author);
  }
}
